const resList = [
    {
      info: {
        id: "720502",
        name: "Chicken Chaska",
        cloudinaryImageId: "0d43fd6c8e2be04402f5ff852b7d9baa",
        locality: "Bisokhar",
        areaName: "Dayapuri",
        costForTwo: "₹250 for two",
        cuisines: ["North Indian", "Indian", "Snacks"],
        avgRatingString: "NEW",
        avgRating: 2.8,
      },
    },
    {
      info: {
        id: "774394",
        name: "Saini Fast Food",
        cloudinaryImageId: "7c0b42a907144cd42b3b319001498a33",
        areaName: "Dayapuri",
        costForTwo: "₹198 for two",
        locality: "Chhoti Market",
        cuisines: ["Chinese", "Burgers", "Pastas"],
        avgRating: 3.2,
      },
    },
    {
      info: {
        id: "612925",
        name: "Gopal Gi Restaurant",
        cloudinaryImageId: "xru62gfjuau8hxv04ik8",
        locality: "Delhi Road \n",
        areaName: "Dayapuri",
        costForTwo: "₹200 for two",
        cuisines: ["North Indian", "Indian"],
        avgRating: 3.2,
      },
    },
    {
      info: {
        id: "612028",
        name: "Donald's Pastry",
        cloudinaryImageId: "apy7s6ygxfo9ma0hxvcr",
        locality: "Meerut Road",
        areaName: "Dayapuri",
        costForTwo: "₹200 for two",
        cuisines: ["Beverages", "Snacks"],
        avgRating: 3.7,
      },
    },
    {
      info: {
        id: "503874",
        name: "Royal Chicken Point",
        cloudinaryImageId: "rzxj9lcoatunqrzalryu",
        locality: "Hapur Road",
        areaName: "Dayapuri",
        costForTwo: "₹400 for two",
        cuisines: ["North Indian", "Tandoor"],
        avgRating: 3.6,
      },
    },
    {
      info: {
        id: "697849",
        name: "Biggest Pizza",
        cloudinaryImageId: "a0fd5a4063f3e053378b00334ef10ab0",
        locality: "Modinagar",
        areaName: "Modinagar Locality",
        costForTwo: "₹500 for two",
        cuisines: ["Pizzas", "Snacks", "Burgers", "Beverages"],
        avgRating: 2.5,
      },
    },
    {
      info: {
        id: "773636",
        name: "Drool Patties",
        cloudinaryImageId: "48938af4f643b6770918be391fe21a42",
        locality: "GT Road",
        areaName: "Dayapuri",
        costForTwo: "₹198 for two",
        cuisines: ["Indian"],
        veg: true,
        avgRating: 4.5,
      },
    },
    {
      info: {
        id: "696630",
        name: "VVIP Pizza",
        cloudinaryImageId: "75a21b4fde096e35e2982d69613d608e",
        locality: "Delhi Meerut Road",
        areaName: "Modinagar Locality",
        costForTwo: "₹400 for two",
        cuisines: ["Pizzas"],
        veg: true,
        avgRating: 3.2,
      },
    },
    {
      info: {
        id: "773585",
        name: "Paras Fast Food",
        cloudinaryImageId: "c3bc32ad3ed9515bb0bf77c419d5a429",
        locality: "Modinagar",
        areaName: "Dayapuri",
        costForTwo: "₹200 for two",
        cuisines: ["Indian"],
        avgRating: 2.5,
      },
    },
    {
      info: {
        id: "696629",
        name: "Kababi Pizza",
        cloudinaryImageId: "75a21b4fde096e35e2982d69613d608e",
        locality: "Delhi Meerut Nagar",
        areaName: "Modinagar Locality",
        costForTwo: "₹300 for two",
        cuisines: ["Pizzas"],
        avgRating: 3.9,
      },
    },
    {
      info: {
        id: "768705",
        name: "Meals Mania",
        cloudinaryImageId: "203b221988ce52724674f77db2382119",
        locality: "Shivpuri",
        areaName: "Dayapuri",
        costForTwo: "₹150 for two",
        cuisines: ["Chinese", "Fast Food"],
        avgRating: 2.1,
      },
    },
    {
      info: {
        id: "716003",
        name: "Pizza 4 You",
        cloudinaryImageId: "dfcf6d9fbd77b2ff1006ccfb40e2ca55",
        locality: "Delhi Meerut Road",
        areaName: "Modinagar Locality",
        costForTwo: "₹400 for two",
        cuisines: ["Pizzas"],
        avgRating: 2.8,
      },
    },
  ];
  
  export default resList; 